xmsextractor: XmUGrid2dDataExtractorUnitTests Class Reference
XmUGrid2dDataExtractorUnitTests Class Reference
Class to to test XmUGrid2dDataExtractor.
Public Member Functions
void testPointScalarsOnly ()
Test extractor with point scalars only.
void testPointScalarCellActivity ()
Test extractor when using point scalars and cell activity.
void testPointScalarPointActivity ()
Test extractor when using point scalars and point activity.
void testInvalidPointScalarsAndActivitySize ()
Test when scalar and activity arrays are sized incorrectly.
void testCellScalarsOnly ()
Test extractor with cell scalars only.
void testCellScalarCellActivity ()
[snip_test_Example_SimpleLocationExtractor]
void testCellScalarCellActivityIdw ()
Test extractor when using cell scalars and cell activity.
void testCellScalarPointActivity ()
Test extractor when using point scalars and point activity.
void testInvalidCellScalarsAndActivitySize ()
Test extractor with cell scalars only.
void testChangingScalarsAndActivity ()
Test extractor going through time steps with cell and point scalars.
void testCopiedExtractor ()
Test extractor built by copying triangles.
void testTutorial ()
Test XmUGrid2dDataExtractor for tutorial.
Detailed Description
Class to to test XmUGrid2dDataExtractor.
Definition at line 24 of file XmUGrid2dDataExtractor.t.h.
Member Function Documentation
testCellScalarCellActivity()
void XmUGrid2dDataExtractorUnitTests::testCellScalarCellActivity ()
[snip_test_Example_SimpleLocationExtractor]
Test extractor when using cell scalars and cell activity.
Definition at line 769 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractor::New().
testCellScalarsOnly()
void XmUGrid2dDataExtractorUnitTests::testCellScalarsOnly ()
Test extractor with cell scalars only.
///  3----2
///  | 1 /|
///  |  / |
///  | /  |
///  |/ 0 |
///  0----1
///
[snip_test_Example_SimpleLocationExtractor]
Definition at line 738 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractor::New().
testPointScalarPointActivity()
void XmUGrid2dDataExtractorUnitTests::testPointScalarPointActivity ()
Test extractor when using point scalars and point activity.
6-—7------—8 point row 3 | / \ /| | / \ / | | / \ / | |/ \ / | 3------—4-—5 point row 2 |\ / \ | | \ / \ | | \ / \ | | \ / | 0-—1------—2 point row 1
Definition at line 624 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractor::New().
testTutorial()
void XmUGrid2dDataExtractorUnitTests::testTutorial ()
Test XmUGrid2dDataExtractor for tutorial.
[snip_test_Example_TransientLocationExtractor]
Definition at line 1117 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractor::New().
The documentation for this class was generated from the following files:
/home/conan/xmsextractor/extractor/XmUGrid2dDataExtractor.t.h
/home/conan/xmsextractor/extractor/XmUGrid2dDataExtractor.cpp