xmsextractor: xms::XmUGrid2dDataExtractorImpl Class Reference
xms::XmUGrid2dDataExtractorImpl Class Reference
Implementation for XmUGrid2dDataExtractor.
Public Member Functions
XmUGrid2dDataExtractorImpl (BSHP< XmUGrid > a_ugrid)
Construct from a UGrid.
XmUGrid2dDataExtractorImpl (BSHP< XmUGrid2dDataExtractorImpl > a_extractor)
Create a new XmUGrid2dDataExtractorImpl using shallow copy from existing extractor.
virtual void SetGridPointScalars (const VecFlt &a_pointScalars, const DynBitset &a_activity, DataLocationEnum a_activityLocation) override
Setup point scalars to be used to extract interpolated data.
virtual void SetGridCellScalars (const VecFlt &a_cellScalars, const DynBitset &a_activity, DataLocationEnum a_activityLocation) override
Setup cell scalars to be used to extract interpolated data.
virtual void SetExtractLocations (const VecPt3d &a_locations) override
Sets locations of points to extract interpolated scalar data from.
virtual void ExtractData (VecFlt &a_outData) override
Extract interpolated data for the previously set locations.
virtual float ExtractAtLocation (const Pt3d &a_location) override
Extract interpolated data for the previously set locations.
virtual void SetUseIdwForPointData (bool a_) override
Set to use IDW to calculate point scalar values from cell scalars.
virtual void SetNoDataValue (float a_value) override
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
virtual void BuildTriangles (DataLocationEnum a_location) override
Build triangles for UGrid for either point or cell scalars.
virtual const BSHP< XmUGridTriangles2d > GetUGridTriangles () const override
Get the UGrid triangles.
virtual const VecFlt & GetScalars () const override
Gets the scalars.
virtual DataLocationEnum GetScalarLocation () const override
Gets the location of the scalars (points or cells)
virtual const VecPt3d & GetExtractLocations () const override
Gets locations of points to extract interpolated scalar data from.
virtual bool GetUseIdwForPointData () const override
Gets the option for using IDW for point data.
virtual float GetNoDataValue () const override
Gets the no data value.
Public Member Functions inherited from xms::XmUGrid2dDataExtractor
virtual ~XmUGrid2dDataExtractor ()
Destructor.
Private Member Functions
void ApplyActivity (const DynBitset &a_activity, DataLocationEnum a_location, DynBitset &a_cellActivity)
Apply point or cell activity to triangles.
void SetGridPointActivity (const DynBitset &a_pointActivity, DynBitset &a_cellActivity)
Set point activity. Turns off each cell attached to an inactive point.
void SetGridCellActivity (const DynBitset &a_cellActivity)
Set activity on cells.
void PushPointDataToCentroids (const DynBitset &a_cellActivity)
Push point scalar data to cell centroids using average.
void PushCellDataToTrianglePoints (const VecFlt &a_cellScalars, const DynBitset &a_cellActivity)
Push cell scalar data to triangle points using cells connected to a point with average or IDW.
float CalculatePointByAverage (const VecInt &a_cellIdxs, const VecFlt &a_cellScalars, const DynBitset &a_cellActivity)
Calculate the average of the cell values connected to a point.
float CalculatePointByIdw (int a_pointIdx, const VecInt &a_cellIdxs, const VecFlt &a_cellScalars, const DynBitset &a_cellActivity)
Calculate the point value by IDW method from surrounding cells.
Private Attributes
BSHP< XmUGrid > m_ugrid
UGrid for dataset.
DataLocationEnum m_triangleType
if triangles been generated for points or cells
BSHP< XmUGridTriangles2d > m_triangles
triangles generated from UGrid to use for data extraction
VecPt3d m_extractLocations
output locations for interpolated values
VecFlt m_pointScalars
scalars to interpolate from
bool m_useIdwForPointData
use IDW to calculate point data from cell data
float m_noDataValue
value to use for inactive result
Additional Inherited Members
Static Public Member Functions inherited from xms::XmUGrid2dDataExtractor
static BSHP< XmUGrid2dDataExtractor > New (BSHP< XmUGrid > a_ugrid)
Create a new XmUGrid2dDataExtractor.
static BSHP< XmUGrid2dDataExtractor > New (BSHP< XmUGrid2dDataExtractor > a_extractor)
Create a new XmUGrid2dDataExtractor using shallow copy from existing extractor.
Protected Member Functions inherited from xms::XmUGrid2dDataExtractor
XmUGrid2dDataExtractor ()
Constructor.
Detailed Description
Implementation for XmUGrid2dDataExtractor.
Implementation for XmUGrid2dDataExtractor which provides ability to extract dataset values at points for an unstructured grid.
Definition at line 51 of file XmUGrid2dDataExtractor.cpp.
Constructor & Destructor Documentation
XmUGrid2dDataExtractorImpl() [1/2]
xms::XmUGrid2dDataExtractorImpl::XmUGrid2dDataExtractorImpl (BSHP< XmUGrid > a_ugrid)
Construct from a UGrid.
Parameters
[in] a_ugrid The UGrid to construct an extractor for.
Definition at line 124 of file XmUGrid2dDataExtractor.cpp.
Referenced by xms::XmUGrid2dDataExtractor::New().
XmUGrid2dDataExtractorImpl() [2/2]
xms::XmUGrid2dDataExtractorImpl::XmUGrid2dDataExtractorImpl (BSHP< XmUGrid2dDataExtractorImpl > a_extractor)
Create a new XmUGrid2dDataExtractorImpl using shallow copy from existing extractor.
Parameters
[in] a_extractor The extractor to shallow copy
Returns
the new XmUGrid2dDataExtractorImpl.
Definition at line 140 of file XmUGrid2dDataExtractor.cpp.
Member Function Documentation
ApplyActivity()
void xms::XmUGrid2dDataExtractorImpl::ApplyActivity (const DynBitset & a_activity, DataLocationEnum a_location, DynBitset & a_cellActivity) private
Apply point or cell activity to triangles.
Parameters
[in] a_activity The activity of the scalar values.
[in] a_location The location of the activity (cells or points).
[out] a_cellActivity The cell activity of the scalar values.
Definition at line 273 of file XmUGrid2dDataExtractor.cpp.
References SetGridCellActivity(), and SetGridPointActivity().
Referenced by GetNoDataValue(), SetGridCellScalars(), and SetGridPointScalars().
BuildTriangles()
void xms::XmUGrid2dDataExtractorImpl::BuildTriangles (DataLocationEnum a_location) override virtual
Build triangles for UGrid for either point or cell scalars.
Parameters
[in] a_location Location to build on (points or cells).
Implements xms::XmUGrid2dDataExtractor.
Definition at line 484 of file XmUGrid2dDataExtractor.cpp.
References m_triangles, m_triangleType, and m_ugrid.
Referenced by SetGridCellScalars(), and SetGridPointScalars().
CalculatePointByAverage()
float xms::XmUGrid2dDataExtractorImpl::CalculatePointByAverage (const VecInt & a_cellIdxs, const VecFlt & a_cellScalars, const DynBitset & a_cellActivity) private
Calculate the average of the cell values connected to a point.
Parameters
[in] a_cellIdxs the cells surrounding the point.
[in] a_cellScalars the cell scalar values.
[in] a_cellActivity the cell activity vector.
Returns
Average of active surrounding cell scalars.
Definition at line 415 of file XmUGrid2dDataExtractor.cpp.
References m_noDataValue.
Referenced by CalculatePointByIdw(), GetNoDataValue(), and PushCellDataToTrianglePoints().
CalculatePointByIdw()
float xms::XmUGrid2dDataExtractorImpl::CalculatePointByIdw (int a_pointIdx, const VecInt & a_cellIdxs, const VecFlt & a_cellScalars, const DynBitset & a_cellActivity) private
Calculate the point value by IDW method from surrounding cells.
Parameters
[in] a_pointIdx the point to calculate the value for.
[in] a_cellIdxs the cells surrounding the point.
[in] a_cellScalars the cell scalar values.
[in] a_cellActivity the cell activity vector.
Returns
IDW interpolated value of active surrounding cell scalars.
Definition at line 444 of file XmUGrid2dDataExtractor.cpp.
References CalculatePointByAverage(), m_triangles, and m_ugrid.
Referenced by GetNoDataValue(), and PushCellDataToTrianglePoints().
ExtractAtLocation()
float xms::XmUGrid2dDataExtractorImpl::ExtractAtLocation (const Pt3d & a_location) override virtual
Extract interpolated data for the previously set locations.
Parameters
[in] a_location The location to get the interpolated scalar.
Returns
The interpolated value.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 242 of file XmUGrid2dDataExtractor.cpp.
References ExtractData(), and SetExtractLocations().
ExtractData()
void xms::XmUGrid2dDataExtractorImpl::ExtractData (VecFlt & a_outData) override virtual
Extract interpolated data for the previously set locations.
Parameters
[out] a_outData The interpolated scalars.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 209 of file XmUGrid2dDataExtractor.cpp.
References m_extractLocations, m_noDataValue, m_pointScalars, and m_triangles.
Referenced by ExtractAtLocation().
GetExtractLocations()
virtual const VecPt3d& xms::XmUGrid2dDataExtractorImpl::GetExtractLocations () const inline override virtual
Gets locations of points to extract interpolated scalar data from.
Returns
The locations.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 82 of file XmUGrid2dDataExtractor.cpp.
References m_extractLocations.
GetNoDataValue()
virtual float xms::XmUGrid2dDataExtractorImpl::GetNoDataValue () const inline override virtual
Gets the no data value.
Returns
The no data value.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 88 of file XmUGrid2dDataExtractor.cpp.
References ApplyActivity(), CalculatePointByAverage(), CalculatePointByIdw(), m_noDataValue, PushCellDataToTrianglePoints(), PushPointDataToCentroids(), SetGridCellActivity(), and SetGridPointActivity().
GetScalarLocation()
virtual DataLocationEnum xms::XmUGrid2dDataExtractorImpl::GetScalarLocation () const inline override virtual
Gets the location of the scalars (points or cells)
Returns
The location of the scalars.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 79 of file XmUGrid2dDataExtractor.cpp.
References m_triangleType.
GetScalars()
virtual const VecFlt& xms::XmUGrid2dDataExtractorImpl::GetScalars () const inline override virtual
Gets the scalars.
Returns
The scalars.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 76 of file XmUGrid2dDataExtractor.cpp.
References m_pointScalars.
GetUGridTriangles()
const BSHP< XmUGridTriangles2d > xms::XmUGrid2dDataExtractorImpl::GetUGridTriangles () const override virtual
Get the UGrid triangles.
Returns
The UGrid triangles.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 497 of file XmUGrid2dDataExtractor.cpp.
References m_triangles.
GetUseIdwForPointData()
virtual bool xms::XmUGrid2dDataExtractorImpl::GetUseIdwForPointData () const inline override virtual
Gets the option for using IDW for point data.
Returns
The option.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 85 of file XmUGrid2dDataExtractor.cpp.
References m_useIdwForPointData.
PushCellDataToTrianglePoints()
void xms::XmUGrid2dDataExtractorImpl::PushCellDataToTrianglePoints (const VecFlt & a_cellScalars, const DynBitset & a_cellActivity) private
Push cell scalar data to triangle points using cells connected to a point with average or IDW.
Parameters
[in] a_cellScalars the cell scalar values.
[in] a_cellActivity the cell activity vector.
Definition at line 380 of file XmUGrid2dDataExtractor.cpp.
References CalculatePointByAverage(), CalculatePointByIdw(), m_pointScalars, m_triangles, m_ugrid, and m_useIdwForPointData.
Referenced by GetNoDataValue(), and SetGridCellScalars().
PushPointDataToCentroids()
void xms::XmUGrid2dDataExtractorImpl::PushPointDataToCentroids (const DynBitset & a_cellActivity) private
Push point scalar data to cell centroids using average.
Parameters
[in] a_cellActivity The cell activity of the scalar values.
Definition at line 350 of file XmUGrid2dDataExtractor.cpp.
References m_pointScalars, m_triangles, and m_ugrid.
Referenced by GetNoDataValue(), and SetGridPointScalars().
SetExtractLocations()
void xms::XmUGrid2dDataExtractorImpl::SetExtractLocations (const VecPt3d & a_locations) override virtual
Sets locations of points to extract interpolated scalar data from.
Parameters
[in] a_locations The locations.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 201 of file XmUGrid2dDataExtractor.cpp.
References m_extractLocations.
Referenced by ExtractAtLocation().
SetGridCellActivity()
void xms::XmUGrid2dDataExtractorImpl::SetGridCellActivity (const DynBitset & a_cellActivity) private
Set activity on cells.
Parameters
[in] a_cellActivity The cell activity of the scalar values.
Definition at line 338 of file XmUGrid2dDataExtractor.cpp.
References m_triangles, and m_ugrid.
Referenced by ApplyActivity(), and GetNoDataValue().
SetGridCellScalars()
void xms::XmUGrid2dDataExtractorImpl::SetGridCellScalars (const VecFlt & a_cellScalars, const DynBitset & a_activity, DataLocationEnum a_activityLocation) override virtual
Setup cell scalars to be used to extract interpolated data.
Parameters
[in] a_cellScalars The point scalars.
[in] a_activity The activity of the cells.
[in] a_activityLocation The location at which the data is currently stored.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 181 of file XmUGrid2dDataExtractor.cpp.
References ApplyActivity(), BuildTriangles(), m_ugrid, and PushCellDataToTrianglePoints().
SetGridPointActivity()
void xms::XmUGrid2dDataExtractorImpl::SetGridPointActivity (const DynBitset & a_pointActivity, DynBitset & a_cellActivity) private
Set point activity. Turns off each cell attached to an inactive point.
Parameters
[in] a_pointActivity The activity for the UGrid points.
[out] a_cellActivity The resulting activity transfered to the cells.
Definition at line 302 of file XmUGrid2dDataExtractor.cpp.
References m_triangles, and m_ugrid.
Referenced by ApplyActivity(), and GetNoDataValue().
SetGridPointScalars()
void xms::XmUGrid2dDataExtractorImpl::SetGridPointScalars (const VecFlt & a_pointScalars, const DynBitset & a_activity, DataLocationEnum a_activityLocation) override virtual
Setup point scalars to be used to extract interpolated data.
Parameters
[in] a_pointScalars The point scalars.
[in] a_activity The activity of the cells.
[in] a_activityLocation The location at which the data is currently stored.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 157 of file XmUGrid2dDataExtractor.cpp.
References ApplyActivity(), BuildTriangles(), m_pointScalars, m_ugrid, and PushPointDataToCentroids().
SetNoDataValue()
void xms::XmUGrid2dDataExtractorImpl::SetNoDataValue (float a_value) override virtual
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
Parameters
[in] a_value The no data value
Implements xms::XmUGrid2dDataExtractor.
Definition at line 263 of file XmUGrid2dDataExtractor.cpp.
References m_noDataValue.
SetUseIdwForPointData()
void xms::XmUGrid2dDataExtractorImpl::SetUseIdwForPointData (bool a_useIdw) override virtual
Set to use IDW to calculate point scalar values from cell scalars.
Parameters
a_useIdw Whether to turn IDW on or off.
Implements xms::XmUGrid2dDataExtractor.
Definition at line 254 of file XmUGrid2dDataExtractor.cpp.
References m_useIdwForPointData.
The documentation for this class was generated from the following file:
/home/conan/xmsextractor/extractor/XmUGrid2dDataExtractor.cpp