xmsextractor: xms::XmUGrid2dPolylineDataExtractor Class Reference
xms::XmUGrid2dPolylineDataExtractor Class Reference abstract
Provides ability to interpolate and extract the scalar values along a polyline for an unstructured grid.
Public Member Functions
virtual ~XmUGrid2dPolylineDataExtractor ()
Destructor.
virtual void SetGridScalars (const VecFlt &a_scalars, const DynBitset &a_activity, DataLocationEnum a_activityLocation)=0
Setup point scalars to be used to extract interpolated data.
virtual void SetPolyline (const VecPt3d &a_polyline)=0
Set the polyline along which to extract the scalar data. Locations crossing cell boundaries are computed along the polyline.
virtual void ExtractData (VecFlt &a_extractedData)=0
Extract data at previously computed locations returned by GetExtractLocations.
virtual void ComputeLocationsAndExtractData (const VecPt3d &a_polyline, VecFlt &a_extractedData, VecPt3d &a_extractedLocations)=0
Extract data for given polyline.
virtual void SetUseIdwForPointData (bool a_useIdw)=0
Set to use IDW to calculate point scalar values from cell scalars.
virtual void SetNoDataValue (float a_noDataValue)=0
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
virtual const VecFlt & GetScalars () const =0
Gets the scalars.
virtual DataLocationEnum GetScalarLocation () const =0
Gets the location of the scalars (points or cells)
virtual const VecPt3d & GetExtractLocations () const =0
Gets computed locations along polyline to extract interpolated scalar data from.
virtual bool GetUseIdwForPointData () const =0
Gets the option for using IDW for point data.
virtual float GetNoDataValue () const =0
Gets the no data value.
Static Public Member Functions
static BSHP< XmUGrid2dPolylineDataExtractor > New (BSHP< XmUGrid > a_ugrid, DataLocationEnum a_scalarLocation)
Create a new XmUGrid2dPolylineDataExtractor.
Protected Member Functions
XmUGrid2dPolylineDataExtractor ()
Constructor.
Detailed Description
Provides ability to interpolate and extract the scalar values along a polyline for an unstructured grid.
Definition at line 39 of file XmUGrid2dPolylineDataExtractor.h.
Member Function Documentation
ComputeLocationsAndExtractData()
virtual void xms::XmUGrid2dPolylineDataExtractor::ComputeLocationsAndExtractData (const VecPt3d & a_polyline, VecFlt & a_extractedData, VecPt3d & a_extractedLocations) pure virtual
Extract data for given polyline.
Parameters
[in] a_polyline The polyline.
[out] a_extractedData The interpolated scalar data at the extracted locations.
[out] a_extractedLocations The locations.
ExtractData()
virtual void xms::XmUGrid2dPolylineDataExtractor::ExtractData (VecFlt & a_extractedData) pure virtual
Extract data at previously computed locations returned by GetExtractLocations.
Parameters
[out] a_extractedData The interpolated scalar data at the previously computed locations.
GetExtractLocations()
virtual const VecPt3d& xms::XmUGrid2dPolylineDataExtractor::GetExtractLocations () const pure virtual
Gets computed locations along polyline to extract interpolated scalar data from.
Returns
The locations.
GetNoDataValue()
virtual float xms::XmUGrid2dPolylineDataExtractor::GetNoDataValue () const pure virtual
Gets the no data value.
Returns
The no data value.
GetScalarLocation()
virtual DataLocationEnum xms::XmUGrid2dPolylineDataExtractor::GetScalarLocation () const pure virtual
Gets the location of the scalars (points or cells)
Returns
The location of the scalars.
GetScalars()
virtual const VecFlt& xms::XmUGrid2dPolylineDataExtractor::GetScalars () const pure virtual
Gets the scalars.
Returns
The scalars.
GetUseIdwForPointData()
virtual bool xms::XmUGrid2dPolylineDataExtractor::GetUseIdwForPointData () const pure virtual
Gets the option for using IDW for point data.
Returns
The option.
New()
BSHP< XmUGrid2dPolylineDataExtractor > xms::XmUGrid2dPolylineDataExtractor::New (BSHP< XmUGrid > a_ugrid, DataLocationEnum a_scalarLocation) static
Create a new XmUGrid2dPolylineDataExtractor.
Parameters
[in] a_ugrid The UGrid geometry to use to extract values from
[in] a_scalarLocation The location of the scalars (points or cells).
Returns
the new XmUGrid2dPolylineDataExtractor
Definition at line 290 of file XmUGrid2dPolylineDataExtractor.cpp.
Referenced by XmUGrid2dPolylineDataExtractorUnitTests::testCellScalars(), XmUGrid2dPolylineDataExtractorUnitTests::testOneCellOneSegment(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentAcrossCellIntoSecond(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentAcrossSplitCells(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentAllInCell(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentAllOutside(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentAlongEdge(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentCrossCellPoint(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentOutToTouch(), XmUGrid2dPolylineDataExtractorUnitTests::testSegmentTouchToOut(), XmUGrid2dPolylineDataExtractorUnitTests::testThreeSegmentsCrossOnBoundary(), XmUGrid2dPolylineDataExtractorUnitTests::testTransientTutorial(), XmUGrid2dPolylineDataExtractorUnitTests::testTwoSegmentsAcrossOneCell(), XmUGrid2dPolylineDataExtractorUnitTests::testTwoSegmentsAllOutside(), XmUGrid2dPolylineDataExtractorUnitTests::testTwoSegmentsFirstExiting(), XmUGrid2dPolylineDataExtractorUnitTests::testTwoSegmentsJoinInCell(), and XmUGrid2dPolylineDataExtractorUnitTests::testTwoSegmentsJoinOnBoundary().
SetGridScalars()
virtual void xms::XmUGrid2dPolylineDataExtractor::SetGridScalars (const VecFlt & a_scalars, const DynBitset & a_activity, DataLocationEnum a_activityLocation) pure virtual
Setup point scalars to be used to extract interpolated data.
Parameters
[in] a_scalars The cell or point scalars.
[in] a_activity The activity of the cells.
[in] a_activityLocation The location at which the data is currently stored.
SetNoDataValue()
virtual void xms::XmUGrid2dPolylineDataExtractor::SetNoDataValue (float a_noDataValue) pure virtual
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
Parameters
[in] a_noDataValue The no data value
SetPolyline()
virtual void xms::XmUGrid2dPolylineDataExtractor::SetPolyline (const VecPt3d & a_polyline) pure virtual
Set the polyline along which to extract the scalar data. Locations crossing cell boundaries are computed along the polyline.
Parameters
[in] a_polyline The polyline.
SetUseIdwForPointData()
virtual void xms::XmUGrid2dPolylineDataExtractor::SetUseIdwForPointData (bool a_useIdw) pure virtual
Set to use IDW to calculate point scalar values from cell scalars.
Parameters
a_useIdw Whether to turn IDW on or off.
The documentation for this class was generated from the following files:
/home/conan/xmsextractor/extractor/XmUGrid2dPolylineDataExtractor.h
/home/conan/xmsextractor/extractor/XmUGrid2dPolylineDataExtractor.cpp