xmsextractor: xms::XmUGrid2dDataExtractor Class Reference
xms::XmUGrid2dDataExtractor Class Reference abstract
Provides ability to interpolate and extract the scalar values points and along arcs for an unstructured grid.
Public Member Functions
virtual ~XmUGrid2dDataExtractor ()
Destructor.
virtual void SetGridPointScalars (const VecFlt &a_pointScalars, const DynBitset &a_activity, DataLocationEnum a_activityType)=0
Setup point scalars to be used to extract interpolated data.
virtual void SetGridCellScalars (const VecFlt &a_cellScalars, const DynBitset &a_activity, DataLocationEnum a_activityType)=0
Setup cell scalars to be used to extract interpolated data.
virtual void SetExtractLocations (const VecPt3d &a_locations)=0
Sets locations of points to extract interpolated scalar data from.
virtual void ExtractData (VecFlt &a_outData)=0
Extract interpolated data for the previously set locations.
virtual float ExtractAtLocation (const Pt3d &a_location)=0
Extract interpolated data for the previously set locations.
virtual void SetUseIdwForPointData (bool a_useIdw)=0
Set to use IDW to calculate point scalar values from cell scalars.
virtual void SetNoDataValue (float a_noDataValue)=0
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
virtual void BuildTriangles (DataLocationEnum a_location)=0
Build triangles for UGrid for either point or cell scalars.
virtual const BSHP< XmUGridTriangles2d > GetUGridTriangles () const =0
Get the UGrid triangles.
virtual const VecFlt & GetScalars () const =0
Gets the scalars.
virtual DataLocationEnum GetScalarLocation () const =0
Gets the location of the scalars (points or cells)
virtual const VecPt3d & GetExtractLocations () const =0
Gets locations of points to extract interpolated scalar data from.
virtual bool GetUseIdwForPointData () const =0
Gets the option for using IDW for point data.
virtual float GetNoDataValue () const =0
Gets the no data value.
Static Public Member Functions
static BSHP< XmUGrid2dDataExtractor > New (BSHP< XmUGrid > a_ugrid)
Create a new XmUGrid2dDataExtractor.
static BSHP< XmUGrid2dDataExtractor > New (BSHP< XmUGrid2dDataExtractor > a_extractor)
Create a new XmUGrid2dDataExtractor using shallow copy from existing extractor.
Protected Member Functions
XmUGrid2dDataExtractor ()
Constructor.
Detailed Description
Provides ability to interpolate and extract the scalar values points and along arcs for an unstructured grid.
Definition at line 42 of file XmUGrid2dDataExtractor.h.
Member Function Documentation
BuildTriangles()
virtual void xms::XmUGrid2dDataExtractor::BuildTriangles (DataLocationEnum a_location) pure virtual
Build triangles for UGrid for either point or cell scalars.
Parameters
[in] a_location Location to build on (points or cells).
Implemented in xms::XmUGrid2dDataExtractorImpl.
ExtractAtLocation()
virtual float xms::XmUGrid2dDataExtractor::ExtractAtLocation (const Pt3d & a_location) pure virtual
Extract interpolated data for the previously set locations.
Parameters
[in] a_location The location to get the interpolated scalar.
Returns
The interpolated value.
Implemented in xms::XmUGrid2dDataExtractorImpl.
ExtractData()
virtual void xms::XmUGrid2dDataExtractor::ExtractData (VecFlt & a_outData) pure virtual
Extract interpolated data for the previously set locations.
Parameters
[out] a_outData The interpolated scalars.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetExtractLocations()
virtual const VecPt3d& xms::XmUGrid2dDataExtractor::GetExtractLocations () const pure virtual
Gets locations of points to extract interpolated scalar data from.
Returns
The locations.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetNoDataValue()
virtual float xms::XmUGrid2dDataExtractor::GetNoDataValue () const pure virtual
Gets the no data value.
Returns
The no data value.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetScalarLocation()
virtual DataLocationEnum xms::XmUGrid2dDataExtractor::GetScalarLocation () const pure virtual
Gets the location of the scalars (points or cells)
Returns
The location of the scalars.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetScalars()
virtual const VecFlt& xms::XmUGrid2dDataExtractor::GetScalars () const pure virtual
Gets the scalars.
Returns
The scalars.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetUGridTriangles()
virtual const BSHP<XmUGridTriangles2d> xms::XmUGrid2dDataExtractor::GetUGridTriangles () const pure virtual
Get the UGrid triangles.
Returns
Shared pointer to triangles.
Implemented in xms::XmUGrid2dDataExtractorImpl.
GetUseIdwForPointData()
virtual bool xms::XmUGrid2dDataExtractor::GetUseIdwForPointData () const pure virtual
Gets the option for using IDW for point data.
Returns
The option.
Implemented in xms::XmUGrid2dDataExtractorImpl.
New() [1/2]
BSHP< XmUGrid2dDataExtractor > xms::XmUGrid2dDataExtractor::New (BSHP< XmUGrid > a_ugrid) static
Create a new XmUGrid2dDataExtractor.
Parameters
[in] a_ugrid The UGrid geometry to use to extract values from
Returns
the new XmUGrid2dDataExtractor
Definition at line 512 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractorImpl::XmUGrid2dDataExtractorImpl().
Referenced by XmUGrid2dDataExtractorUnitTests::testCellScalarCellActivity(), XmUGrid2dDataExtractorUnitTests::testCellScalarCellActivityIdw(), XmUGrid2dDataExtractorUnitTests::testCellScalarPointActivity(), XmUGrid2dDataExtractorUnitTests::testCellScalarsOnly(), XmUGrid2dDataExtractorUnitTests::testChangingScalarsAndActivity(), XmUGrid2dDataExtractorUnitTests::testCopiedExtractor(), XmUGrid2dDataExtractorUnitTests::testInvalidCellScalarsAndActivitySize(), XmUGrid2dDataExtractorUnitTests::testInvalidPointScalarsAndActivitySize(), XmUGrid2dDataExtractorUnitTests::testPointScalarCellActivity(), XmUGrid2dDataExtractorUnitTests::testPointScalarPointActivity(), XmUGrid2dDataExtractorUnitTests::testPointScalarsOnly(), and XmUGrid2dDataExtractorUnitTests::testTutorial().
New() [2/2]
BSHP< XmUGrid2dDataExtractor > xms::XmUGrid2dDataExtractor::New (BSHP< XmUGrid2dDataExtractor > a_extractor) static
Create a new XmUGrid2dDataExtractor using shallow copy from existing extractor.
Parameters
[in] a_extractor The extractor to shallow copy
Returns
the new XmUGrid2dDataExtractor.
Definition at line 523 of file XmUGrid2dDataExtractor.cpp.
References xms::XmUGrid2dDataExtractorImpl::XmUGrid2dDataExtractorImpl().
SetExtractLocations()
virtual void xms::XmUGrid2dDataExtractor::SetExtractLocations (const VecPt3d & a_locations) pure virtual
Sets locations of points to extract interpolated scalar data from.
Parameters
[in] a_locations The locations.
Implemented in xms::XmUGrid2dDataExtractorImpl.
SetGridCellScalars()
virtual void xms::XmUGrid2dDataExtractor::SetGridCellScalars (const VecFlt & a_cellScalars, const DynBitset & a_activity, DataLocationEnum a_activityType) pure virtual
Setup cell scalars to be used to extract interpolated data.
Parameters
[in] a_cellScalars The point scalars.
[in] a_activity The activity of the cells.
[in] a_activityType The location at which the data is currently stored.
Implemented in xms::XmUGrid2dDataExtractorImpl.
SetGridPointScalars()
virtual void xms::XmUGrid2dDataExtractor::SetGridPointScalars (const VecFlt & a_pointScalars, const DynBitset & a_activity, DataLocationEnum a_activityType) pure virtual
Setup point scalars to be used to extract interpolated data.
Parameters
[in] a_pointScalars The point scalars.
[in] a_activity The activity of the cells.
[in] a_activityType The location at which the data is currently stored.
Implemented in xms::XmUGrid2dDataExtractorImpl.
SetNoDataValue()
virtual void xms::XmUGrid2dDataExtractor::SetNoDataValue (float a_noDataValue) pure virtual
Set value to use when extracted value is in inactive cell or doesn't intersect with the grid.
Parameters
[in] a_noDataValue The no data value
Implemented in xms::XmUGrid2dDataExtractorImpl.
SetUseIdwForPointData()
virtual void xms::XmUGrid2dDataExtractor::SetUseIdwForPointData (bool a_useIdw) pure virtual
Set to use IDW to calculate point scalar values from cell scalars.
Parameters
a_useIdw Whether to turn IDW on or off.
Implemented in xms::XmUGrid2dDataExtractorImpl.
The documentation for this class was generated from the following files:
/home/conan/xmsextractor/extractor/XmUGrid2dDataExtractor.h
/home/conan/xmsextractor/extractor/XmUGrid2dDataExtractor.cpp